import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserContextProvider } from "./context/UserContext";
import { ImGithub } from "react-icons/im";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <header>
            <ImGithub size="3rem" />
            <h1>GitHub Finder</h1>
            <p>Histórico de pesquisa</p>
          </header>
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
