import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MdHistory } from "react-icons/md";
import { UserContextProvider } from "./context/UserContext";
import { ImGithub } from "react-icons/im";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GitHub Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <header>
            <div className="logoContainer">
              <ImGithub size="3rem" />
              <Link href="/">
                <h1>GitHub Finder</h1>
              </Link>
            </div>

            <Link href="/history" className="historySearch">
              <MdHistory size="1.7rem" />

              <span>Pesquisados recentemente</span>
            </Link>
          </header>
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
